.Dd June 13, 2026
.Dt LIBPFF 3
.Os
.Sh NAME
.Nm libpff.h
.Nd Library to access the Personal Folder File (OST, PAB and PST) format
.Sh SYNOPSIS
.In libpff.h
.Pp
Support functions
.nf
.Ft const char *
.Fo libpff_get_version
.Fa "void"
.Fc
.fi
.nf
.Ft int
.Fo libpff_get_access_flags_read
.Fa "void"
.Fc
.fi
.nf
.Ft int
.Fo libpff_get_codepage
.Fa "int *codepage"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_set_codepage
.Fa "int codepage"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_check_file_signature
.Fa "const char *filename"
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Available when compiled with wide character string support:
.nf
.Ft int
.Fo libpff_check_file_signature_wide
.Fa "const wchar_t *filename"
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Available when compiled with libbfio support:
.nf
.Ft int
.Fo libpff_check_file_signature_file_io_handle
.Fa "libbfio_handle_t *file_io_handle"
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Notify functions
.nf
.Ft void
.Fo libpff_notify_set_verbose
.Fa "int verbose"
.Fc
.fi
.nf
.Ft int
.Fo libpff_notify_set_stream
.Fa "FILE *stream"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_notify_stream_open
.Fa "const char *filename"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_notify_stream_close
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Error functions
.nf
.Ft void
.Fo libpff_error_free
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_error_fprint
.Fa "libpff_error_t *error"
.Fa "FILE *stream"
.Fc
.fi
.nf
.Ft int
.Fo libpff_error_sprint
.Fa "libpff_error_t *error"
.Fa "char *string"
.Fa "size_t size"
.Fc
.fi
.nf
.Ft int
.Fo libpff_error_backtrace_fprint
.Fa "libpff_error_t *error"
.Fa "FILE *stream"
.Fc
.fi
.nf
.Ft int
.Fo libpff_error_backtrace_sprint
.Fa "libpff_error_t *error"
.Fa "char *string"
.Fa "size_t size"
.Fc
.fi
.Pp
File functions
.nf
.Ft int
.Fo libpff_file_initialize
.Fa "libpff_file_t **file"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_free
.Fa "libpff_file_t **file"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_signal_abort
.Fa "libpff_file_t *file"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_open
.Fa "libpff_file_t *file"
.Fa "const char *filename"
.Fa "int access_flags"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_close
.Fa "libpff_file_t *file"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_is_corrupted
.Fa "libpff_file_t *file"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_recover_items
.Fa "libpff_file_t *file"
.Fa "uint8_t recovery_flags"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_size
.Fa "libpff_file_t *file"
.Fa "size64_t *size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_content_type
.Fa "libpff_file_t *file"
.Fa "uint8_t *content_type"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_type
.Fa "libpff_file_t *file"
.Fa "uint8_t *type"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_encryption_type
.Fa "libpff_file_t *file"
.Fa "uint8_t *encryption_type"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_ascii_codepage
.Fa "libpff_file_t *file"
.Fa "int *ascii_codepage"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_set_ascii_codepage
.Fa "libpff_file_t *file"
.Fa "int ascii_codepage"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_number_of_unallocated_blocks
.Fa "libpff_file_t *file"
.Fa "int unallocated_block_type"
.Fa "int *number_of_unallocated_blocks"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_unallocated_block
.Fa "libpff_file_t *file"
.Fa "int unallocated_block_type"
.Fa "int unallocated_block_index"
.Fa "off64_t *offset"
.Fa "size64_t *size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_root_item
.Fa "libpff_file_t *file"
.Fa "libpff_item_t **root_item"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_message_store
.Fa "libpff_file_t *file"
.Fa "libpff_item_t **message_store"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_name_to_id_map
.Fa "libpff_file_t *file"
.Fa "libpff_item_t **name_to_id_map"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_root_folder
.Fa "libpff_file_t *file"
.Fa "libpff_item_t **root_folder"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_item_by_identifier
.Fa "libpff_file_t *file"
.Fa "uint32_t item_identifier"
.Fa "libpff_item_t **item"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_number_of_orphan_items
.Fa "libpff_file_t *file"
.Fa "int *number_of_orphan_items"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_orphan_item_by_index
.Fa "libpff_file_t *file"
.Fa "int orphan_item_index"
.Fa "libpff_item_t **orphan_item"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_number_of_recovered_items
.Fa "libpff_file_t *file"
.Fa "int *number_of_recovered_items"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_file_get_recovered_item_by_index
.Fa "libpff_file_t *file"
.Fa "int recovered_item_index"
.Fa "libpff_item_t **recovered_item"
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Available when compiled with wide character string support:
.nf
.Ft int
.Fo libpff_file_open_wide
.Fa "libpff_file_t *file"
.Fa "const wchar_t *filename"
.Fa "int access_flags"
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Available when compiled with libbfio support:
.nf
.Ft int
.Fo libpff_file_open_file_io_handle
.Fa "libpff_file_t *file"
.Fa "libbfio_handle_t *file_io_handle"
.Fa "int access_flags"
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Item functions
.nf
.Ft int
.Fo libpff_item_free
.Fa "libpff_item_t **item"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_item_get_identifier
.Fa "libpff_item_t *item"
.Fa "uint32_t *identifier"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_item_get_number_of_record_sets
.Fa "libpff_item_t *item"
.Fa "int *number_of_record_sets"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_item_get_record_set_by_index
.Fa "libpff_item_t *item"
.Fa "int record_set_index"
.Fa "libpff_record_set_t **record_set"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_item_get_number_of_entries
.Fa "libpff_item_t *item"
.Fa "uint32_t *number_of_entries"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_item_get_type
.Fa "libpff_item_t *item"
.Fa "uint8_t *item_type"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_item_get_number_of_sub_items
.Fa "libpff_item_t *item"
.Fa "int *number_of_sub_items"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_item_get_sub_item
.Fa "libpff_item_t *item"
.Fa "int sub_item_index"
.Fa "libpff_item_t **sub_item"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_item_get_sub_item_by_identifier
.Fa "libpff_item_t *item"
.Fa "uint32_t sub_item_identifier"
.Fa "libpff_item_t **sub_item"
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Name to ID map entry functions
.nf
.Ft int
.Fo libpff_name_to_id_map_entry_get_type
.Fa "libpff_name_to_id_map_entry_t *name_to_id_map_entry"
.Fa "uint8_t *entry_type"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_name_to_id_map_entry_get_number
.Fa "libpff_name_to_id_map_entry_t *name_to_id_map_entry"
.Fa "uint32_t *number"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_name_to_id_map_entry_get_utf8_string_size
.Fa "libpff_name_to_id_map_entry_t *name_to_id_map_entry"
.Fa "size_t *utf8_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_name_to_id_map_entry_get_utf8_string
.Fa "libpff_name_to_id_map_entry_t *name_to_id_map_entry"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_name_to_id_map_entry_get_utf16_string_size
.Fa "libpff_name_to_id_map_entry_t *name_to_id_map_entry"
.Fa "size_t *utf16_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_name_to_id_map_entry_get_utf16_string
.Fa "libpff_name_to_id_map_entry_t *name_to_id_map_entry"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_name_to_id_map_entry_get_guid
.Fa "libpff_name_to_id_map_entry_t *name_to_id_map_entry"
.Fa "uint8_t *guid"
.Fa "size_t size"
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Record set functions
.nf
.Ft int
.Fo libpff_record_set_free
.Fa "libpff_record_set_t **record_set"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_set_get_number_of_entries
.Fa "libpff_record_set_t *record_set"
.Fa "int *number_of_entries"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_set_get_entry_by_index
.Fa "libpff_record_set_t *record_set"
.Fa "int record_entry_index"
.Fa "libpff_record_entry_t **record_entry"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_set_get_entry_by_type
.Fa "libpff_record_set_t *record_set"
.Fa "uint32_t entry_type"
.Fa "uint32_t value_type"
.Fa "libpff_record_entry_t **record_entry"
.Fa "uint8_t flags"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_set_get_entry_by_utf8_name
.Fa "libpff_record_set_t *record_set"
.Fa "const uint8_t *utf8_string"
.Fa "size_t utf8_string_length"
.Fa "uint32_t value_type"
.Fa "libpff_record_entry_t **record_entry"
.Fa "uint8_t flags"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_set_get_entry_by_utf16_name
.Fa "libpff_record_set_t *record_set"
.Fa "const uint16_t *utf16_string"
.Fa "size_t utf16_string_length"
.Fa "uint32_t value_type"
.Fa "libpff_record_entry_t **record_entry"
.Fa "uint8_t flags"
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Record entry functions
.nf
.Ft int
.Fo libpff_record_entry_free
.Fa "libpff_record_entry_t **record_entry"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_entry_type
.Fa "libpff_record_entry_t *record_entry"
.Fa "uint32_t *entry_type"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_value_type
.Fa "libpff_record_entry_t *record_entry"
.Fa "uint32_t *value_type"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_name_to_id_map_entry
.Fa "libpff_record_entry_t *record_entry"
.Fa "libpff_name_to_id_map_entry_t **name_to_id_map_entry"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data_size
.Fa "libpff_record_entry_t *record_entry"
.Fa "size_t *data_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data
.Fa "libpff_record_entry_t *record_entry"
.Fa "uint8_t *data"
.Fa "size_t data_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data_as_boolean
.Fa "libpff_record_entry_t *record_entry"
.Fa "uint8_t *value_boolean"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data_as_16bit_integer
.Fa "libpff_record_entry_t *record_entry"
.Fa "uint16_t *value_16bit"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data_as_32bit_integer
.Fa "libpff_record_entry_t *record_entry"
.Fa "uint32_t *value_32bit"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data_as_64bit_integer
.Fa "libpff_record_entry_t *record_entry"
.Fa "uint64_t *value_64bit"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data_as_filetime
.Fa "libpff_record_entry_t *record_entry"
.Fa "uint64_t *filetime"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data_as_floatingtime
.Fa "libpff_record_entry_t *record_entry"
.Fa "uint64_t *floatingtime"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data_as_size
.Fa "libpff_record_entry_t *record_entry"
.Fa "size64_t *value_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data_as_floating_point
.Fa "libpff_record_entry_t *record_entry"
.Fa "double *value_floating_point"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data_as_utf8_string_size
.Fa "libpff_record_entry_t *record_entry"
.Fa "size_t *utf8_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data_as_utf8_string
.Fa "libpff_record_entry_t *record_entry"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data_as_utf16_string_size
.Fa "libpff_record_entry_t *record_entry"
.Fa "size_t *utf16_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data_as_utf16_string
.Fa "libpff_record_entry_t *record_entry"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_data_as_guid
.Fa "libpff_record_entry_t *record_entry"
.Fa "uint8_t *guid_data"
.Fa "size_t guid_data_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_record_entry_get_multi_value
.Fa "libpff_record_entry_t *record_entry"
.Fa "libpff_multi_value_t **multi_value"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft ssize_t
.Fo libpff_record_entry_read_buffer
.Fa "libpff_record_entry_t *record_entry"
.Fa "uint8_t *buffer"
.Fa "size_t buffer_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft off64_t
.Fo libpff_record_entry_seek_offset
.Fa "libpff_record_entry_t *record_entry"
.Fa "off64_t offset"
.Fa "int whence"
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Multi value functions
.nf
.Ft int
.Fo libpff_multi_value_free
.Fa "libpff_multi_value_t **multi_value"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_multi_value_get_number_of_values
.Fa "libpff_multi_value_t *multi_value"
.Fa "int *number_of_values"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_multi_value_get_value
.Fa "libpff_multi_value_t *multi_value"
.Fa "int value_index"
.Fa "uint32_t *value_type"
.Fa "uint8_t **value_data"
.Fa "size_t *value_data_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_multi_value_get_value_32bit
.Fa "libpff_multi_value_t *multi_value"
.Fa "int value_index"
.Fa "uint32_t *value_32bit"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_multi_value_get_value_64bit
.Fa "libpff_multi_value_t *multi_value"
.Fa "int value_index"
.Fa "uint64_t *value_64bit"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_multi_value_get_value_filetime
.Fa "libpff_multi_value_t *multi_value"
.Fa "int value_index"
.Fa "uint64_t *value_64bit"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_multi_value_get_value_utf8_string_size
.Fa "libpff_multi_value_t *multi_value"
.Fa "int value_index"
.Fa "size_t *utf8_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_multi_value_get_value_utf8_string
.Fa "libpff_multi_value_t *multi_value"
.Fa "int value_index"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_multi_value_get_value_utf16_string_size
.Fa "libpff_multi_value_t *multi_value"
.Fa "int value_index"
.Fa "size_t *utf16_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_multi_value_get_value_utf16_string
.Fa "libpff_multi_value_t *multi_value"
.Fa "int value_index"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_multi_value_get_value_binary_data_size
.Fa "libpff_multi_value_t *multi_value"
.Fa "int value_index"
.Fa "size_t *size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_multi_value_get_value_binary_data
.Fa "libpff_multi_value_t *multi_value"
.Fa "int value_index"
.Fa "uint8_t *binary_data"
.Fa "size_t size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_multi_value_get_value_guid
.Fa "libpff_multi_value_t *multi_value"
.Fa "int value_index"
.Fa "uint8_t *guid"
.Fa "size_t size"
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Folder item functions
.nf
.Ft int
.Fo libpff_folder_get_type
.Fa "libpff_item_t *folder"
.Fa "uint8_t *type"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_utf8_name_size
.Fa "libpff_item_t *folder"
.Fa "size_t *utf8_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_utf8_name
.Fa "libpff_item_t *folder"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_utf16_name_size
.Fa "libpff_item_t *folder"
.Fa "size_t *utf16_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_utf16_name
.Fa "libpff_item_t *folder"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_number_of_sub_folders
.Fa "libpff_item_t *folder"
.Fa "int *number_of_sub_folders"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_sub_folder
.Fa "libpff_item_t *folder"
.Fa "int sub_folder_index"
.Fa "libpff_item_t **sub_folder"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_sub_folder_by_utf8_name
.Fa "libpff_item_t *folder"
.Fa "uint8_t *utf8_sub_folder_name"
.Fa "size_t utf8_sub_folder_name_size"
.Fa "libpff_item_t **sub_folder"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_sub_folder_by_utf16_name
.Fa "libpff_item_t *folder"
.Fa "uint16_t *utf16_sub_folder_name"
.Fa "size_t utf16_sub_folder_name_size"
.Fa "libpff_item_t **sub_folder"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_sub_folders
.Fa "libpff_item_t *folder"
.Fa "libpff_item_t **sub_folders"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_number_of_sub_messages
.Fa "libpff_item_t *folder"
.Fa "int *number_of_sub_messages"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_sub_message
.Fa "libpff_item_t *folder"
.Fa "int sub_message_index"
.Fa "libpff_item_t **sub_message"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_sub_message_by_utf8_name
.Fa "libpff_item_t *folder"
.Fa "uint8_t *utf8_sub_message_name"
.Fa "size_t utf8_sub_message_name_size"
.Fa "libpff_item_t **sub_message"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_sub_message_by_utf16_name
.Fa "libpff_item_t *folder"
.Fa "uint16_t *utf16_sub_message_name"
.Fa "size_t utf16_sub_message_name_size"
.Fa "libpff_item_t **sub_message"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_sub_messages
.Fa "libpff_item_t *folder"
.Fa "libpff_item_t **sub_messages"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_number_of_sub_associated_contents
.Fa "libpff_item_t *folder"
.Fa "int *number_of_sub_associated_contents"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_sub_associated_content
.Fa "libpff_item_t *folder"
.Fa "int sub_associated_content_index"
.Fa "libpff_item_t **sub_associated_content"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_sub_associated_contents
.Fa "libpff_item_t *folder"
.Fa "libpff_item_t **sub_associated_contents"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_folder_get_unknowns
.Fa "libpff_item_t *folder"
.Fa "libpff_item_t **unknowns"
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Message item functions
.nf
.Ft int
.Fo libpff_message_get_entry_value_utf8_string_size
.Fa "libpff_item_t *message"
.Fa "uint32_t entry_type"
.Fa "size_t *utf8_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_entry_value_utf8_string
.Fa "libpff_item_t *message"
.Fa "uint32_t entry_type"
.Fa "uint8_t *utf8_string"
.Fa "size_t utf8_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_entry_value_utf16_string_size
.Fa "libpff_item_t *message"
.Fa "uint32_t entry_type"
.Fa "size_t *utf16_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_entry_value_utf16_string
.Fa "libpff_item_t *message"
.Fa "uint32_t entry_type"
.Fa "uint16_t *utf16_string"
.Fa "size_t utf16_string_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_client_submit_time
.Fa "libpff_item_t *message"
.Fa "uint64_t *filetime"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_delivery_time
.Fa "libpff_item_t *message"
.Fa "uint64_t *filetime"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_creation_time
.Fa "libpff_item_t *message"
.Fa "uint64_t *filetime"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_modification_time
.Fa "libpff_item_t *message"
.Fa "uint64_t *filetime"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_number_of_attachments
.Fa "libpff_item_t *message"
.Fa "int *number_of_attachments"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_attachment
.Fa "libpff_item_t *message"
.Fa "int attachment_index"
.Fa "libpff_item_t **attachment"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_attachments
.Fa "libpff_item_t *message"
.Fa "libpff_item_t **attachments"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_recipients
.Fa "libpff_item_t *message"
.Fa "libpff_item_t **recipients"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_plain_text_body_size
.Fa "libpff_item_t *message"
.Fa "size_t *size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_plain_text_body
.Fa "libpff_item_t *message"
.Fa "uint8_t *message_body"
.Fa "size_t size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_rtf_body_size
.Fa "libpff_item_t *message"
.Fa "size_t *size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_rtf_body
.Fa "libpff_item_t *message"
.Fa "uint8_t *message_body"
.Fa "size_t size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_html_body_size
.Fa "libpff_item_t *message"
.Fa "size_t *size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_message_get_html_body
.Fa "libpff_item_t *message"
.Fa "uint8_t *message_body"
.Fa "size_t size"
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Attachment item functions
.nf
.Ft int
.Fo libpff_attachment_get_type
.Fa "libpff_item_t *attachment"
.Fa "int *attachment_type"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_attachment_get_data_size
.Fa "libpff_item_t *attachment"
.Fa "size64_t *size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft ssize_t
.Fo libpff_attachment_data_read_buffer
.Fa "libpff_item_t *attachment"
.Fa "uint8_t *buffer"
.Fa "size_t buffer_size"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft off64_t
.Fo libpff_attachment_data_seek_offset
.Fa "libpff_item_t *attachment"
.Fa "off64_t offset"
.Fa "int whence"
.Fa "libpff_error_t **error"
.Fc
.fi
.nf
.Ft int
.Fo libpff_attachment_get_item
.Fa "libpff_item_t *attachment"
.Fa "libpff_item_t **attached_item"
.Fa "libpff_error_t **error"
.Fc
.fi
.Pp
Available when compiled with libbfio support:
.nf
.Ft int
.Fo libpff_attachment_get_data_file_io_handle
.Fa "libpff_item_t *attachment"
.Fa "libbfio_handle_t **file_io_handle"
.Fa "libpff_error_t **error"
.Fc
.fi
.Sh DESCRIPTION
The
.Fn libpff_get_version
function is used to retrieve the library version.
.Sh RETURN VALUES
Most of the functions return NULL or \-1 on error, dependent on the return \
type.
For the actual return values see
.In libpff.h .
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh NOTES
libpff can be compiled with wide character support (wchar_t).
.sp
To compile libpff with wide character support use:
.Ar ./configure --enable-wide-character-type
 or define:
.Ar _UNICODE
 or
.Ar UNICODE
 during compilation.
.sp
.Ar LIBPFF_WIDE_CHARACTER_TYPE
 in libpff/features.h can be used to determine if libpff was compiled with wide character support.
.Sh SEE ALSO
.In libpff.h
.Sh AUTHORS
.An Joachim Metz <joachim.metz@gmail.com>
.Sh BUGS
Please report bugs of any kind on the project issue tracker: \
https://github.com/libyal/libpff/issues
.Sh COPYRIGHT
Copyright (C) 2008-2026, Joachim Metz <joachim.metz@gmail.com>.
.sp
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A \
PARTICULAR PURPOSE.
