.Dd March 16, 2019
.Dt pffinfo
.Os libpff
.Sh NAME
.Nm pffinfo
.Nd determines information about a Personal Folder File (OST, PAB and PST)
.Sh SYNOPSIS
.Nm pffinfo
.Op Fl c Ar codepage
.Op Fl ahvV
.Ar source
.Sh DESCRIPTION
.Nm pffinfo
is a utility to determine information about a Personal Folder File (OST, PAB and PST)
.Pp
.Nm pffinfo
is part of the
.Nm libpff
package.
.Nm libpff
is a library to access the Personal Folder File (OST, PAB and PST) format
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl a
shows allocation information
.It Fl c Ar codepage
specify the codepage of ASCII strings, options: ascii, windows-874, windows-932, windows-936, windows-949, windows-950, windows-1250, windows-1251, windows-1252 (default), windows-1253, windows-1254, windows-1255, windows-1256, windows-1257 or windows-1258
.It Fl h
shows this help
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# pffinfo -a file.pst
pffinfo 20110107

Personal Folder File information:
	File size:		271360 bytes
	File content type:	Personal Storage Tables (PST)
	File type:		64-bit
	Encryption type:	compressible

Message store:
	Folders:		Subtree, Wastbox, Finder
	Password checksum:	N/A

Unallocated index node blocks:
	00018944 (0x00004a00) - 00020480 (0x00005000) size: 1536
.Dl        ...
	01051648 (0x00100c00) - 01052160 (0x00100e00) size: 512

Unallocated data blocks:
	00025024 (0x000061c0) - 00025536 (0x000063c0) size: 512
.Dl        ...
	01353664 (0x0014a7c0) - 01541120 (0x00178400) size: 187456

.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
https://github.com/libyal/libpff/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright (C) 2008-2023, Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
.Xr pffexport 1
