# Build OSSFuzz fuzz targets from source.
name: build_ossfuzz
on:
  push:
    branches: [main]
permissions: read-all
jobs:
  build_ossfuzz:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
        - architecture: 'x64'
          compiler: 'gcc'
          configure_options: ''
    steps:
    - name: Install build dependencies
      run: |
        sudo apt-get -y install git
    - uses: actions/checkout@v4
      with:
        repository: google/oss-fuzz
        path: oss-fuzz
    - name: Build OSSFuzz fuzz targets
      working-directory: oss-fuzz
      run: |
        mkdir -p projects/libpff
        cp projects/libyal/build.sh projects/libpff/
        cp projects/libyal/project.yaml projects/libpff/
        head -n 20 projects/libyal/Dockerfile > projects/libpff/Dockerfile
        echo "RUN git clone --depth 1 https://github.com/libyal/libpff.git libpff" >> projects/libpff/Dockerfile
        tail -n 3 projects/libyal/Dockerfile >> projects/libpff/Dockerfile
        python3 infra/helper.py build_image --pull libpff
        python3 infra/helper.py build_fuzzers --sanitizer address libpff
        python3 infra/helper.py check_build libpff
